In [6]:
import numpy as np
import pandas as pd
from pathlib import Path

In [12]:
layer_0_11_res = '/home/user1/dropdead72/second_git_folder/results_llama_2_0_11/llama_tensorllm_results_0_11.csv'
layer_11_21_res = '/home/user1/dropdead72/second_git_folder/results_llama_2_11_21/llama_tensorllm_results_11_21.csv'
layer_21_32_res = '/home/user1/dropdead72/second_git_folder/results_llama_2_21_32/llama_tensorllm_results_21_32.csv'

In [13]:
result_paths = [layer_0_11_res, layer_11_21_res, layer_21_32_res]
dataframes = []

In [15]:
for layer in result_paths:
    df = pd.read_csv(layer)
    dataframes.append(df)

In [16]:
combined_df = pd.concat(dataframes, ignore_index=True)

In [19]:
norm_names = []
cos_names = []

for col in combined_df.columns:
    if 'norm' in col:
        norm_names.append(col)
    
    if 'cos' in col:
        cos_names.append(col)

In [24]:
disp_norms = ['diff_norm_after_mha_og_vs_method_mean',
              'diff_norm_after_mha_residual_og_vs_method_mean',
              'diff_norm_after_mlp_og_vs_method_mean',
              'diff_norm_after_layer_og_vs_method_mean',
              'diff_norm_delta_layer_og_vs_method_mean',
              'diff_norm_delta_mha_og_vs_method_mean',
              'diff_norm_delta_mlp_to_layer_og_vs_method_mean']

cos_norms = [
    'cos_after_mha_og_vs_method_mean',
    'cos_after_mha_residual_og_vs_method_mean',
    'cos_after_mlp_og_vs_method_mean',
    'cos_after_layer_og_vs_method_mean',
    'cos_delta_layer_og_vs_method_mean',
    'cos_delta_mha_og_vs_method_mean',
    'cos_delta_mlp_to_layer_og_vs_method_mean'
]

general = [
    'target_set',
    'method_label'
]

# Norms

In [34]:
'perplexoty' in combined_df.columns

False

In [ ]:
ppl_wikitext2,ppl_c4,wikitext2_ppl

In [50]:
combined_df[general + ['ppl_wikitext2', 'ppl_c4', 'wikitext2_ppl']][combined_df['method_label'] == "tucker_per_head_mha"]

,target_set,method_label,ppl_wikitext2,ppl_c4,wikitext2_ppl
4,llama_all_layer_0,tucker_per_head_mha,12.257545,13.877623,12.257545
13,llama_all_layer_1,tucker_per_head_mha,11.658448,16.158340,11.658448
22,llama_all_layer_2,tucker_per_head_mha,5.670854,7.129430,5.670854
31,llama_all_layer_3,tucker_per_head_mha,5.431196,7.013175,5.431196
40,llama_all_layer_4,tucker_per_head_mha,5.321825,6.913890,5.321825
49,llama_all_layer_5,tucker_per_head_mha,5.346741,6.935177,5.346741
58,llama_all_layer_6,tucker_per_head_mha,5.427426,6.992352,5.427426
67,llama_all_layer_7,tucker_per_head_mha,5.334928,6.921905,5.334928
76,llama_all_layer_8,tucker_per_head_mha,5.265830,6.792943,5.265830
85,llama_all_layer_9,tucker_per_head_mha,5.272960,6.841528,5.272960
94,llama_all_layer_10,tucker_per_head_mha,5.369815,6.884838,5.369815
104,llama_all_layer_11,tucker_per_head_mha,5.242339,6.792847,5.242339
113,llama_all_layer_12,tucker_per_head_mha,5.239810,6.787088,5.239810
122,llama_all_layer_13,tucker_per_head_mha,5.294469,6.844441,5.294469
131,llama_all_layer_14,tucker_per_head_mha,5.236421,6.783266,5.236421
140,llama_all_layer_15,tucker_per_head_mha,5.257596,6.797006,5.257596
149,llama_all_layer_16,tucker_per_head_mha,5.258709,6.833208,5.258709
158,llama_all_layer_17,tucker_per_head_mha,5.218215,6.762236,5.218215
167,llama_all_layer_18,tucker_per_head_mha,5.208218,6.758653,5.208218
176,llama_all_layer_19,tucker_per_head_mha,5.201910,6.735556,5.201910
185,llama_all_layer_20,tucker_per_head_mha,5.181691,6.743565,5.181691
195,llama_all_layer_21,tucker_per_head_mha,5.168781,6.719217,5.168781
204,llama_all_layer_22,tucker_per_head_mha,5.189989,6.729339,5.189989
213,llama_all_layer_23,tucker_per_head_mha,5.164404,6.707608,5.164404
222,llama_all_layer_24,tucker_per_head_mha,5.155238,6.705425,5.155238
231,llama_all_layer_25,tucker_per_head_mha,5.328779,6.709176,5.328779
240,llama_all_layer_26,tucker_per_head_mha,5.201910,6.712216,5.201910
249,llama_all_layer_27,tucker_per_head_mha,5.145663,6.694018,5.145663
258,llama_all_layer_28,tucker_per_head_mha,5.218768,6.723904,5.218768
267,llama_all_layer_29,tucker_per_head_mha,5.219935,6.698721,5.219935
276,llama_all_layer_30,tucker_per_head_mha,5.214962,6.761614,5.214962
285,llama_all_layer_31,tucker_per_head_mha,5.238701,6.742685,5.238701

In [55]:
combined_df[general + ['ppl_wikitext2', 'ppl_c4', 'wikitext2_ppl']][combined_df['method_label'] == "tensorllm_mha"]

,target_set,method_label,ppl_wikitext2,ppl_c4,wikitext2_ppl
5,llama_all_layer_0,tensorllm_mha,333.338440,176.456223,333.338440
14,llama_all_layer_1,tensorllm_mha,18.631683,23.861629,18.631683
23,llama_all_layer_2,tensorllm_mha,5.601359,7.233937,5.601359
32,llama_all_layer_3,tensorllm_mha,5.420789,6.920162,5.420789
41,llama_all_layer_4,tensorllm_mha,5.326899,6.954121,5.326899
50,llama_all_layer_5,tensorllm_mha,5.414351,7.003253,5.414351
59,llama_all_layer_6,tensorllm_mha,5.350328,6.831336,5.350328
68,llama_all_layer_7,tensorllm_mha,5.254690,6.801248,5.254690
77,llama_all_layer_8,tensorllm_mha,5.278484,6.799074,5.278484
86,llama_all_layer_9,tensorllm_mha,5.295964,6.860332,5.295964
95,llama_all_layer_10,tensorllm_mha,5.448989,6.953637,5.448989
105,llama_all_layer_11,tensorllm_mha,5.251104,6.810569,5.251104
114,llama_all_layer_12,tensorllm_mha,5.259390,6.802242,5.259390
123,llama_all_layer_13,tensorllm_mha,5.337124,6.848671,5.337124
132,llama_all_layer_14,tensorllm_mha,5.241783,6.787193,5.241783
141,llama_all_layer_15,tensorllm_mha,5.284636,6.822851,5.284636
150,llama_all_layer_16,tensorllm_mha,5.282585,6.872882,5.282585
159,llama_all_layer_17,tensorllm_mha,5.268742,6.763573,5.268742
168,llama_all_layer_18,tensorllm_mha,5.199829,6.741700,5.199829
177,llama_all_layer_19,tensorllm_mha,5.203991,6.738263,5.203991
186,llama_all_layer_20,tensorllm_mha,5.199523,6.760376,5.199523
196,llama_all_layer_21,tensorllm_mha,5.172371,6.723135,5.172371
205,llama_all_layer_22,tensorllm_mha,5.192370,6.735023,5.192370
214,llama_all_layer_23,tensorllm_mha,5.174257,6.717628,5.174257
223,llama_all_layer_24,tensorllm_mha,5.157422,6.711357,5.157422
232,llama_all_layer_25,tensorllm_mha,5.433880,6.696711,5.433880
241,llama_all_layer_26,tensorllm_mha,5.230755,6.720513,5.230755
250,llama_all_layer_27,tensorllm_mha,5.152448,6.705702,5.152448
259,llama_all_layer_28,tensorllm_mha,5.260690,6.808105,5.260690
268,llama_all_layer_29,tensorllm_mha,5.268433,6.712367,5.268433
277,llama_all_layer_30,tensorllm_mha,5.221962,6.730183,5.221962
286,llama_all_layer_31,tensorllm_mha,5.258833,6.770951,5.258833

In [48]:
combined_df

,target_set,model_arch_key,model_family,model_name,method_label,rank,target_modules,target_layers,storage_records,affected_modules_dense_bits,...,norm_ratio_delta_mlp_to_layer_method_over_og_std,norm_ratio_delta_mlp_to_layer_method_over_og_num_tokens,diff_norm_delta_mlp_to_layer_og_vs_method_mean,diff_norm_delta_mlp_to_layer_og_vs_method_median,diff_norm_delta_mlp_to_layer_og_vs_method_std,diff_norm_delta_mlp_to_layer_og_vs_method_num_tokens,rel_diff_norm_delta_mlp_to_layer_og_vs_method_mean,rel_diff_norm_delta_mlp_to_layer_og_vs_method_median,rel_diff_norm_delta_mlp_to_layer_og_vs_method_std,rel_diff_norm_delta_mlp_to_layer_og_vs_method_num_tokens
0,__model_baseline__,llama2,llama,meta-llama/Llama-2-7b-hf,baseline,NaN,[],[],[],0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,llama_all_layer_0,llama2,llama,meta-llama/Llama-2-7b-hf,laser_mha,64.0,"['model.layers.0.self_attn.q_proj', 'model.lay...",[0],[{'full_name': 'model.layers.0.self_attn.q_pro...,1073741824,...,0.350358,102400.0,1.046871,0.995979,0.225132,102400.0,1.375187,1.347018,0.388842,102400.0
2,llama_all_layer_0,llama2,llama,meta-llama/Llama-2-7b-hf,laser_ffn,64.0,"['model.layers.0.mlp.gate_proj', 'model.layers...",[0],"[{'full_name': 'model.layers.0.mlp.gate_proj',...",2164260864,...,0.109422,102400.0,0.406303,0.399925,0.131914,102400.0,0.519366,0.546282,0.125973,102400.0
3,llama_all_layer_0,llama2,llama,meta-llama/Llama-2-7b-hf,tt_per_head_mha,64.0,"['model.layers.0.self_attn.q_proj', 'model.lay...",[0],[{'full_name': 'model.layers.0.self_attn.q_pro...,1073741824,...,0.820393,102400.0,1.116913,0.917520,0.646348,102400.0,1.425655,1.177474,0.720388,102400.0
4,llama_all_layer_0,llama2,llama,meta-llama/Llama-2-7b-hf,tucker_per_head_mha,64.0,"['model.layers.0.self_attn.q_proj', 'model.lay...",[0],[{'full_name': 'model.layers.0.self_attn.q_pro...,1073741824,...,0.290360,102400.0,0.676610,0.590039,0.322887,102400.0,0.847313,0.823584,0.278032,102400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,llama_all_layer_31,llama2,llama,meta-llama/Llama-2-7b-hf,tensorllm_mha,64.0,"['model.layers.31.self_attn.q_proj', 'model.la...",[31],[{'full_name': 'model.layers.31.self_attn.q_pr...,1073741824,...,0.075746,102400.0,37.313412,34.633995,17.849306,102400.0,0.309223,0.289352,0.119960,102400.0
287,llama_all_layer_31,llama2,llama,meta-llama/Llama-2-7b-hf,tensorllm_ffn,64.0,"['model.layers.31.mlp.gate_proj', 'model.layer...",[31],[{'full_name': 'model.layers.31.mlp.gate_proj'...,2164260864,...,0.117216,102400.0,84.803917,84.624344,22.550030,102400.0,0.713009,0.699471,0.110634,102400.0
288,llama_all_layer_31,llama2,llama,meta-llama/Llama-2-7b-hf,tensorllm_mha_ffn,64.0,"['model.layers.31.self_attn.q_proj', 'model.la...",[31],[{'full_name': 'model.layers.31.self_attn.q_pr...,3238002688,...,0.126990,102400.0,90.269257,90.859077,25.085632,102400.0,0.754872,0.751319,0.108727,102400.0
289,llama_all_layer_31,llama2,llama,meta-llama/Llama-2-7b-hf,tensorllm_mha_sep_last,64.0,"['model.layers.31.self_attn.q_proj', 'model.la...",[31],[{'full_name': 'model.layers.31.self_attn.q_pr...,1073741824,...,0.068161,102400.0,33.568642,30.529633,17.604988,102400.0,0.276317,0.253311,0.119002,102400.0
290,llama_all_layer_31,llama2,llama,meta-llama/Llama-2-7b-hf,tensorllm_mha_sep_last__ffn,64.0,"['model.layers.31.self_attn.q_proj', 'model.la...",[31],[{'full_name': 'model.layers.31.self_attn.q_pr...,3238002688,...,0.118926,102400.0,90.612381,91.141716,25.204973,102400.0,0.758056,0.754233,0.111490,102400.0

In [46]:
combined_df[general + disp_norms][combined_df['method_label'] == 'tucker_per_head_mha']

,target_set,method_label,diff_norm_after_mha_og_vs_method_mean,diff_norm_after_mha_residual_og_vs_method_mean,diff_norm_after_mlp_og_vs_method_mean,diff_norm_after_layer_og_vs_method_mean,diff_norm_delta_layer_og_vs_method_mean,diff_norm_delta_mha_og_vs_method_mean,diff_norm_delta_mlp_to_layer_og_vs_method_mean
4,llama_all_layer_0,tucker_per_head_mha,0.578720,0.578716,0.676610,0.879305,0.879305,0.578716,0.676610
13,llama_all_layer_1,tucker_per_head_mha,0.955477,0.955478,2.587952,2.967457,2.967457,0.955478,2.588067
22,llama_all_layer_2,tucker_per_head_mha,1.237244,1.237233,1.162177,1.636384,1.636384,1.237233,1.162229
31,llama_all_layer_3,tucker_per_head_mha,1.812667,1.812663,2.007010,2.306911,2.306911,1.812663,2.007027
40,llama_all_layer_4,tucker_per_head_mha,2.317887,2.317878,2.553274,2.827699,2.827699,2.317878,2.553364
49,llama_all_layer_5,tucker_per_head_mha,2.838829,2.838806,2.692698,3.515505,3.515505,2.838806,2.692717
58,llama_all_layer_6,tucker_per_head_mha,3.679066,3.679054,3.214785,4.332686,4.332686,3.679054,3.214799
67,llama_all_layer_7,tucker_per_head_mha,4.098503,4.098496,3.719077,4.807607,4.807607,4.098496,3.719105
76,llama_all_layer_8,tucker_per_head_mha,4.293284,4.293281,3.532246,4.608800,4.608800,4.293281,3.532258
85,llama_all_layer_9,tucker_per_head_mha,4.907075,4.907070,3.831521,5.262589,5.262589,4.907070,3.831539
94,llama_all_layer_10,tucker_per_head_mha,5.569326,5.569323,4.120553,5.719708,5.719708,5.569323,4.120570
104,llama_all_layer_11,tucker_per_head_mha,5.545016,5.545012,3.668703,5.389542,5.389542,5.545012,3.668720
113,llama_all_layer_12,tucker_per_head_mha,6.034557,6.034588,3.916565,5.895030,5.895030,6.034588,3.916584
122,llama_all_layer_13,tucker_per_head_mha,6.399327,6.399353,4.239833,6.574975,6.574975,6.399353,4.239853
131,llama_all_layer_14,tucker_per_head_mha,6.519728,6.519723,3.852458,6.455991,6.455991,6.519723,3.852479
140,llama_all_layer_15,tucker_per_head_mha,7.043324,7.043315,4.208579,7.183383,7.183383,7.043315,4.208601
149,llama_all_layer_16,tucker_per_head_mha,8.566422,8.566421,5.056726,9.049769,9.049769,8.566421,5.056756
158,llama_all_layer_17,tucker_per_head_mha,7.779286,7.779283,3.785571,7.947522,7.947522,7.779283,3.785609
167,llama_all_layer_18,tucker_per_head_mha,8.788198,8.788164,3.892798,9.386653,9.386653,8.788164,3.892846
176,llama_all_layer_19,tucker_per_head_mha,8.049391,8.049381,3.324921,8.438382,8.438382,8.049381,3.324973
185,llama_all_layer_20,tucker_per_head_mha,11.168797,11.168775,4.305866,11.800881,11.800881,11.168775,4.305911
195,llama_all_layer_21,tucker_per_head_mha,7.618385,7.618450,2.775006,8.022070,8.022070,7.618450,2.775080
204,llama_all_layer_22,tucker_per_head_mha,12.889170,12.889240,3.274565,13.328139,13.328139,12.889240,3.274642
213,llama_all_layer_23,tucker_per_head_mha,8.409619,8.409668,2.704930,8.799816,8.799816,8.409668,2.705048
222,llama_all_layer_24,tucker_per_head_mha,9.849606,9.849640,2.835403,10.213544,10.213544,9.849640,2.835523
231,llama_all_layer_25,tucker_per_head_mha,12.998913,12.998920,4.389109,13.828183,13.828183,12.998920,4.389199
240,llama_all_layer_26,tucker_per_head_mha,12.401277,12.401299,3.498001,12.908817,12.908817,12.401299,3.498125
249,llama_all_layer_27,tucker_per_head_mha,10.645588,10.645614,3.481292,11.118342,11.118342,10.645614,3.481467
258,llama_all_layer_28,tucker_per_head_mha,13.734575,13.734655,4.470610,14.296695,14.296695,13.734655,4.470749
267,llama_all_layer_29,tucker_per_head_mha,14.414342,14.414371,4.654917,15.087895,15.087895,14.414371,4.655272
276,llama_all_layer_30,tucker_per_head_mha,16.693130,16.693157,7.764387,18.456875,18.456875,16.693157,7.764492
285,llama_all_layer_31,tucker_per_head_mha,18.291008,18.291025,19.398937,24.756842,24.756842,18.291025,19.399040

# Angles

In [53]:
combined_df[general + cos_norms][combined_df['method_label'] == 'tucker_per_head_mha']

,target_set,method_label,cos_after_mha_og_vs_method_mean,cos_after_mha_residual_og_vs_method_mean,cos_after_mlp_og_vs_method_mean,cos_after_layer_og_vs_method_mean,cos_delta_layer_og_vs_method_mean,cos_delta_mha_og_vs_method_mean,cos_delta_mlp_to_layer_og_vs_method_mean
4,llama_all_layer_0,tucker_per_head_mha,0.861644,0.903553,0.880758,0.889278,0.799683,0.861645,0.880758
13,llama_all_layer_1,tucker_per_head_mha,0.486768,0.875818,0.673644,0.828244,0.620021,0.486767,0.673644
22,llama_all_layer_2,tucker_per_head_mha,0.449486,0.914382,0.720108,0.888205,0.634909,0.449486,0.720108
31,llama_all_layer_3,tucker_per_head_mha,0.486538,0.916790,0.680098,0.884364,0.592205,0.486544,0.680098
40,llama_all_layer_4,tucker_per_head_mha,0.462298,0.922305,0.694922,0.897586,0.630299,0.462304,0.694922
49,llama_all_layer_5,tucker_per_head_mha,0.271087,0.925318,0.763519,0.898443,0.646758,0.271091,0.763519
58,llama_all_layer_6,tucker_per_head_mha,0.131722,0.913217,0.762298,0.889343,0.614977,0.131722,0.762298
67,llama_all_layer_7,tucker_per_head_mha,0.133826,0.921471,0.768897,0.901085,0.649936,0.133823,0.768896
76,llama_all_layer_8,tucker_per_head_mha,0.236650,0.935850,0.816756,0.930425,0.718293,0.236643,0.816756
85,llama_all_layer_9,tucker_per_head_mha,0.147973,0.934116,0.815458,0.928863,0.699917,0.147975,0.815458
94,llama_all_layer_10,tucker_per_head_mha,0.182665,0.936091,0.814934,0.933826,0.691603,0.182663,0.814934
104,llama_all_layer_11,tucker_per_head_mha,0.169006,0.945323,0.866449,0.949479,0.749647,0.169001,0.866449
113,llama_all_layer_12,tucker_per_head_mha,0.133903,0.946639,0.866139,0.949635,0.741242,0.133894,0.866139
122,llama_all_layer_13,tucker_per_head_mha,0.198373,0.951214,0.874376,0.951184,0.747366,0.198355,0.874376
131,llama_all_layer_14,tucker_per_head_mha,0.152135,0.956423,0.906873,0.959927,0.782681,0.152136,0.906873
140,llama_all_layer_15,tucker_per_head_mha,0.238124,0.959256,0.911963,0.961976,0.794485,0.238124,0.911963
149,llama_all_layer_16,tucker_per_head_mha,0.203123,0.956606,0.903492,0.957485,0.767580,0.203121,0.903492
158,llama_all_layer_17,tucker_per_head_mha,0.182612,0.971131,0.951713,0.973567,0.828311,0.182609,0.951713
167,llama_all_layer_18,tucker_per_head_mha,0.029847,0.971281,0.956581,0.971919,0.796348,0.029851,0.956581
176,llama_all_layer_19,tucker_per_head_mha,0.036765,0.980530,0.970568,0.981464,0.844640,0.036764,0.970569
185,llama_all_layer_20,tucker_per_head_mha,-0.016473,0.973188,0.963192,0.974592,0.771804,-0.016469,0.963192
195,llama_all_layer_21,tucker_per_head_mha,0.116879,0.989142,0.983392,0.989332,0.879850,0.116867,0.983392
204,llama_all_layer_22,tucker_per_head_mha,-0.163472,0.977379,0.978990,0.978316,0.735231,-0.163478,0.978990
213,llama_all_layer_23,tucker_per_head_mha,0.246118,0.990526,0.984605,0.990514,0.876279,0.246107,0.984605
222,llama_all_layer_24,tucker_per_head_mha,0.315321,0.990872,0.985497,0.990945,0.856167,0.315316,0.985497
231,llama_all_layer_25,tucker_per_head_mha,0.099359,0.985618,0.969980,0.984596,0.792906,0.099358,0.969980
240,llama_all_layer_26,tucker_per_head_mha,0.276051,0.989639,0.983252,0.989369,0.825995,0.276046,0.983252
249,llama_all_layer_27,tucker_per_head_mha,0.218229,0.992004,0.983976,0.991710,0.873921,0.218230,0.983976
258,llama_all_layer_28,tucker_per_head_mha,0.238616,0.989838,0.979025,0.989640,0.843953,0.238606,0.979024
267,llama_all_layer_29,tucker_per_head_mha,0.298196,0.990444,0.983830,0.990273,0.865947,0.298189,0.983830
276,llama_all_layer_30,tucker_per_head_mha,0.107415,0.988748,0.982253,0.986951,0.901206,0.107415,0.982254
285,llama_all_layer_31,tucker_per_head_mha,0.433289,0.989177,0.987494,0.988228,0.979439,0.433289,0.987493

In [54]:
combined_df[general + cos_norms][combined_df['method_label'] == 'tensorllm_mha']

,target_set,method_label,cos_after_mha_og_vs_method_mean,cos_after_mha_residual_og_vs_method_mean,cos_after_mlp_og_vs_method_mean,cos_after_layer_og_vs_method_mean,cos_delta_layer_og_vs_method_mean,cos_delta_mha_og_vs_method_mean,cos_delta_mlp_to_layer_og_vs_method_mean
5,llama_all_layer_0,tensorllm_mha,0.070447,0.607938,0.801365,0.783879,0.607052,0.060653,0.801364
14,llama_all_layer_1,tensorllm_mha,0.045156,0.839239,0.568599,0.773922,0.463408,-0.000344,0.568599
23,llama_all_layer_2,tensorllm_mha,-0.012796,0.925290,0.682289,0.893635,0.586925,-0.006203,0.682289
32,llama_all_layer_3,tensorllm_mha,-0.010627,0.924056,0.779502,0.894156,0.614179,0.017417,0.779502
41,llama_all_layer_4,tensorllm_mha,0.005707,0.930351,0.782544,0.908743,0.670411,-0.023497,0.782544
50,llama_all_layer_5,tensorllm_mha,-0.003271,0.930847,0.757066,0.901044,0.626556,0.018537,0.757066
59,llama_all_layer_6,tensorllm_mha,-0.003328,0.935689,0.795745,0.917599,0.678972,-0.012628,0.795745
68,llama_all_layer_7,tensorllm_mha,0.019104,0.941735,0.827188,0.928014,0.721120,0.021614,0.827187
77,llama_all_layer_8,tensorllm_mha,0.011265,0.937855,0.817465,0.926987,0.705573,-0.002169,0.817465
86,llama_all_layer_9,tensorllm_mha,0.015254,0.937325,0.808290,0.929266,0.696332,0.001257,0.808290
95,llama_all_layer_10,tensorllm_mha,0.014012,0.936073,0.800426,0.929602,0.669699,-0.002533,0.800426
105,llama_all_layer_11,tensorllm_mha,-0.015008,0.948283,0.865018,0.949659,0.748187,-0.001510,0.865018
114,llama_all_layer_12,tensorllm_mha,-0.013441,0.949504,0.866874,0.949555,0.738573,0.000233,0.866874
123,llama_all_layer_13,tensorllm_mha,-0.020943,0.951348,0.868566,0.949753,0.735524,-0.000035,0.868566
132,llama_all_layer_14,tensorllm_mha,-0.006695,0.956893,0.904844,0.959584,0.779550,0.000293,0.904844
141,llama_all_layer_15,tensorllm_mha,-0.007919,0.958227,0.902138,0.959659,0.779880,0.001537,0.902138
150,llama_all_layer_16,tensorllm_mha,0.021447,0.955493,0.889947,0.953928,0.744739,0.006994,0.889947
159,llama_all_layer_17,tensorllm_mha,0.014247,0.972765,0.950650,0.974630,0.833754,0.000880,0.950651
168,llama_all_layer_18,tensorllm_mha,0.017310,0.978989,0.962587,0.979906,0.848050,0.006794,0.962587
177,llama_all_layer_19,tensorllm_mha,0.012305,0.983325,0.971237,0.983970,0.865558,0.003817,0.971237
186,llama_all_layer_20,tensorllm_mha,-0.029668,0.981707,0.957194,0.980923,0.833275,-0.004362,0.957194
196,llama_all_layer_21,tensorllm_mha,0.018492,0.989654,0.984264,0.990032,0.886623,-0.000409,0.984264
205,llama_all_layer_22,tensorllm_mha,-0.027849,0.986152,0.977811,0.986361,0.829197,-0.003245,0.977811
214,llama_all_layer_23,tensorllm_mha,-0.013041,0.990086,0.983351,0.990057,0.868710,-0.010982,0.983351
223,llama_all_layer_24,tensorllm_mha,-0.006824,0.990100,0.984164,0.990125,0.834709,-0.002065,0.984164
232,llama_all_layer_25,tensorllm_mha,-0.004745,0.988219,0.974283,0.987867,0.827350,-0.000979,0.974283
241,llama_all_layer_26,tensorllm_mha,0.473345,0.990458,0.981131,0.990088,0.839760,0.473335,0.981131
250,llama_all_layer_27,tensorllm_mha,0.004084,0.991502,0.982324,0.991218,0.864857,-0.001012,0.982324
259,llama_all_layer_28,tensorllm_mha,-0.360293,0.987995,0.975396,0.987931,0.813567,-0.360244,0.975395
268,llama_all_layer_29,tensorllm_mha,-0.468751,0.988316,0.979457,0.988037,0.830677,-0.468782,0.979457
277,llama_all_layer_30,tensorllm_mha,-0.420985,0.981948,0.982428,0.980997,0.854119,-0.420970,0.982428
286,llama_all_layer_31,tensorllm_mha,-0.232861,0.975187,0.944973,0.971534,0.947836,-0.232867,0.944973